### ISSUE TITLE
How to annotate data points with your template?

### ISSUE THREAD

**Issue by hhhhzzzzz** [vlf-silkie/VLFeedback#11]
Hi,

Could you tell me how to annotate data points with your template: https://github.com/vlf-silkie/VLFeedback/blob/main/annotation_template.py?

Manually or by machine?

**Comment by TobiasLee** [comment]
Hi, you can feed this template as a user message to query GPT-4V with corresponding values filled (responses generated) along with the image.

**Comment by hhhhzzzzz** [comment]
Thanks a lot!
