### ISSUE TITLE
The prompt of gpt4v.

### ISSUE THREAD

**Issue by eyuansu62** [vlf-silkie/VLFeedback#4]
Great work!
Could you share the prompt you used for prompting gpt4v?

**Comment by TobiasLee** [comment]
Thanks for your interest.
We uploaded the annotation prompt for GPT4v, check it here:
https://github.com/vlf-silkie/VLFeedback/blob/main/annotation_template.py

**Comment by eyuansu62** [comment]
Thank you for your response. I am seeking clarification on the process of input integration in GPT-4. Are all contextual elements inputted into the GPT-4v simultaneously, or are three prompts fed in separately? Additionally, is this prompt categorized under system messages or user messages

**Comment by TobiasLee** [comment]
- All contextual elements are fed into GPT-4V simultaneously.
- This prompt is fed as a user prompt.
