### ISSUE TITLE
Is it normal for the loss to converge to 0.3 at the end of training? 

### ISSUE THREAD

**Issue by linhaojia13** [vlf-silkie/VLFeedback#8]
Is it normal for the loss to converge to 0.3 at the end of training? Could you provide the training log files? This would help me to compare and verify the correctness of my reproduced experiments."
![图片](https://github.com/vlf-silkie/VLFeedback/assets/38275612/09c67f03-9efb-4e4e-9ea8-0330efd4d02b)

**Comment by TobiasLee** [comment]
@fffffarmer

**Comment by zhxieml** [comment]
> Is it normal for the loss to converge to 0.3 at the end of training? Could you provide the training log files? This would help me to compare and verify the correctness of my reproduced experiments." ![图片](https://private-user-images.githubusercontent.com/38275612/296142824-09c67f03-9efb-4e4e-9ea8-0330efd4d02b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMDkyODAsIm5iZiI6MTcwNTMwODk4MCwicGF0aCI6Ii8zODI3NTYxMi8yOTYxNDI4MjQtMDljNjdmMDMtOWVmYi00ZTRlLTllYTgtMDMzMGVmZDRkMDJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA4NTYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmOWRkOGEzNTFhYWY0ZjMzOTQ0Yzk0ZDU4YTgzODA2MzE1ODE0OTI1YjJjNmNlNmNlNjUyMDVjZDI4MDJkMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xczjyLY7EgTe-aNuhQTBDKfaxSbe4oyItYDcFqmJM2A)

The loss curve looks good to me. Below is the loss curve from our experiment for your reference.

![image](https://github.com/vlf-silkie/VLFeedback/assets/32692131/1f178bdc-4e9f-48ea-aeca-ea162674b8be)

**Comment by linhaojia13** [comment]
Thank you very much!
